language: python
python:
  - "3.2"
  - "3.3"
install:
  - python setup.py install
script: python -m tornado.test.runtests nacho.test
notifications:
  irc: "irc.freenode.org#nacho"
  on_success: "never"
