language: python
python:
  - "3.3"
install:
  - pip install -r requirements.txt
  - python setup.py install
script: python tests/runtests.py
notifications:
  irc: "irc.freenode.org#nacho"
  on_success: "never"
